export default [
	{
		code: 'Backquote',
		contents: { en: '`', ru: 'ё' },
		shift: { en: '~', ru: 'Ё' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'Digit1',
		contents: { en: '1', ru: '1' },
		shift: { en: '!', ru: '!' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit2',
		contents: { en: '2', ru: '2' },
		shift: { en: '@', ru: '"' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit3',
		contents: { en: '3', ru: '3' },
		shift: { en: '#', ru: '№' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit4',
		contents: { en: '4', ru: '4' },
		shift: { en: '$', ru: ';' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit5',
		contents: { en: '5', ru: '5' },
		shift: { en: '%', ru: '%' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit6',
		contents: { en: '6', ru: '6' },
		shift: { en: '^', ru: ':' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit7',
		contents: { en: '7', ru: '7' },
		shift: { en: '&', ru: '?' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit8',
		contents: { en: '8', ru: '8' },
		shift: { en: '*', ru: '*' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit9',
		contents: { en: '9', ru: '9' },
		shift: { en: '(', ru: '(' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Digit0',
		contents: { en: '0', ru: '0' },
		shift: { en: ')', ru: ')' },
		language: { en: 'digit', ru: 'digit' },
	},
	{
		code: 'Minus',
		contents: { en: '-', ru: '-' },
		shift: { en: '_', ru: '_' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'Equal',
		contents: { en: '=', ru: '=' },
		shift: { en: '+', ru: '+' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'Backspace',
		contents: { en: 'Backspace', ru: 'Backspace' },
		shift: { en: 'Backspace', ru: 'Backspace' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'Tab',
		contents: { en: 'Tab', ru: 'Tab' },
		shift: { en: 'Tab', ru: 'Tab' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'KeyQ',
		contents: { en: 'q', ru: 'й' },
		shift: { en: 'Q', ru: 'Й' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyW',
		contents: { en: 'w', ru: 'ц' },
		shift: { en: 'W', ru: 'Ц' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyE',
		contents: { en: 'e', ru: 'у' },
		shift: { en: 'E', ru: 'У' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyR',
		contents: { en: 'r', ru: 'к' },
		shift: { en: 'R', ru: 'К' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyT',
		contents: { en: 't', ru: 'е' },
		shift: { en: 'T', ru: 'Е' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyY',
		contents: { en: 'y', ru: 'н' },
		shift: { en: 'Y', ru: 'Н' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyU',
		contents: { en: 'u', ru: 'г' },
		shift: { en: 'U', ru: 'Г' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyI',
		contents: { en: 'i', ru: 'ш' },
		shift: { en: 'I', ru: 'Ш' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyO',
		contents: { en: 'o', ru: 'щ' },
		shift: { en: 'O', ru: 'Щ' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyP',
		contents: { en: 'p', ru: 'з' },
		shift: { en: 'P', ru: 'З' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'BracketLeft',
		contents: { en: '[', ru: 'х' },
		shift: { en: '{', ru: 'Х' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'BracketRight',
		contents: { en: ']', ru: 'ъ' },
		shift: { en: '}', ru: 'Ъ' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'Backslash',
		contents: { en: '\\', ru: '\\' },
		shift: { en: '|', ru: '/' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'Delete',
		contents: { en: 'Del', ru: 'Del' },
		shift: { en: 'Del', ru: 'Del' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'CapsLock',
		contents: { en: 'CapsLock', ru: 'CapsLock' },
		shift: { en: 'CapsLock', ru: 'CapsLock' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'KeyA',
		contents: { en: 'a', ru: 'ф' },
		shift: { en: 'A', ru: 'Ф' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyS',
		contents: { en: 's', ru: 'ы' },
		shift: { en: 'S', ru: 'Ы' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyD',
		contents: { en: 'd', ru: 'в' },
		shift: { en: 'D', ru: 'В' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyF',
		contents: { en: 'f', ru: 'а' },
		shift: { en: 'F', ru: 'А' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyG',
		contents: { en: 'g', ru: 'п' },
		shift: { en: 'G', ru: 'П' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyH',
		contents: { en: 'h', ru: 'р' },
		shift: { en: 'H', ru: 'Р' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyJ',
		contents: { en: 'j', ru: 'о' },
		shift: { en: 'J', ru: 'О' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyK',
		contents: { en: 'k', ru: 'л' },
		shift: { en: 'K', ru: 'Л' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyL',
		contents: { en: 'l', ru: 'д' },
		shift: { en: 'L', ru: 'Д' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'Semicolon',
		contents: { en: ';', ru: 'ж' },
		shift: { en: ':', ru: 'Ж' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'Quote',
		contents: { en: "'", ru: 'э' },
		shift: { en: '"', ru: 'Э' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'Enter',
		contents: { en: 'Enter', ru: 'Enter' },
		shift: { en: 'Enter', ru: 'Enter' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'ShiftLeft',
		contents: { en: 'Shift', ru: 'Shift' },
		shift: { en: 'Shift', ru: 'Shift' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'KeyZ',
		contents: { en: 'z', ru: 'я' },
		shift: { en: 'Z', ru: 'Я' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyX',
		contents: { en: 'x', ru: 'ч' },
		shift: { en: 'X', ru: 'Ч' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyC',
		contents: { en: 'c', ru: 'с' },
		shift: { en: 'C', ru: 'С' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyV',
		contents: { en: 'v', ru: 'м' },
		shift: { en: 'V', ru: 'М' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyB',
		contents: { en: 'b', ru: 'и' },
		shift: { en: 'B', ru: 'И' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyN',
		contents: { en: 'n', ru: 'т' },
		shift: { en: 'N', ru: 'Т' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'KeyM',
		contents: { en: 'm', ru: 'ь' },
		shift: { en: 'M', ru: 'Ь' },
		language: { en: 'letter', ru: 'letter' },
	},
	{
		code: 'Comma',
		contents: { en: ',', ru: 'б' },
		shift: { en: '<', ru: 'Б' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'Period',
		contents: { en: '.', ru: 'ю' },
		shift: { en: '>', ru: 'Ю' },
		language: { en: 'symbol', ru: 'letter' },
	},
	{
		code: 'Slash',
		contents: { en: '/', ru: '.' },
		shift: { en: '?', ru: ',' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'ArrowUp',
		contents: { en: '▲', ru: '▲' },
		shift: { en: '▲', ru: '▲' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'ShiftRight',
		contents: { en: 'Shift', ru: 'Shift' },
		shift: { en: 'Shift', ru: 'Shift' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'ControlLeft',
		contents: { en: 'Ctrl', ru: 'Ctrl' },
		shift: { en: 'Ctrl', ru: 'Ctrl' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'AltLeft',
		contents: { en: 'Alt', ru: 'Alt' },
		shift: { en: 'Alt', ru: 'Alt' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'Space',
		contents: { en: ' ', ru: ' ' },
		shift: { en: ' ', ru: ' ' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'AltRight',
		contents: { en: 'Alt', ru: 'Alt' },
		shift: { en: 'Alt', ru: 'Alt' },
		language: { en: 'func', ru: 'func' },
	},
	{
		code: 'ArrowLeft',
		contents: { en: '◄', ru: '◄' },
		shift: { en: '◄', ru: '◄' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'ArrowDown',
		contents: { en: '▼', ru: '▼' },
		shift: { en: '▼', ru: '▼' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'ArrowRight',
		contents: { en: '►', ru: '►' },
		shift: { en: '►', ru: '►' },
		language: { en: 'symbol', ru: 'symbol' },
	},
	{
		code: 'ControlRight',
		contents: { en: 'Ctrl', ru: 'Ctrl' },
		shift: { en: 'Ctrl', ru: 'Ctrl' },
		language: { en: 'func', ru: 'func' },
	},
];
